### PR TITLE
dockerfile-add-scanner: update dependencies

### PR DESCRIPTION
**Pull request by christoph-zededa**
perhaps it then supports `COPY --exclude` in Dockerfiles?

### CODE REVIEW

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
@christoph-zededa it looks good, and should solve the issue, but there are conflicts. Can you resolve?

**Comment by deitch** [comment]
Something about the build is off?

**Comment by christoph-zededa** [comment]
> Something about the build is off?

It looks like this certain version of ca-certificates is not available anymore ...

**Comment by deitch** [comment]
Yeah, it is typical of how alpine works. Oh well.

**Pull request merged**
